package Chapter2._2_Exceptions;
public class ExceptionChallenge {
    /**
     * An exception is an unexpected event that occurs during our program.
     * Most likely, you have already encountered an Exception (ArrayIndexOutOfBounds, etc).
     * In order for our program to compile, Java needs to be prepared for how to handle an exception -
     * for instance, you could use a try/catch block to prepare some code in a 'catch' for the event that an exception
     * fires, or you can use a throws declaration to pass on an exception to whatever called the method.
     * (if an exception is thrown from main, Java will crash.)
     *
     * Write a method to throw an exception (you will also need to add a 'throws' declaration to allow the method
     * to compile.)
     */
    public void mustThrow(){
    }
}